version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  labels:
    - "python"
    - "dependencies"
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  labels:
    - ".NET"
    - "dependencies"
  ignore:
    - dependency-name: "aws*"
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  labels:
    - "GH actions"
    - "dependencies"
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  labels:
    - "docker"
    - "dependencies"
  ignore:
    - dependency-name: "mono"
  open-pull-requests-limit: 10
