files:
  - source: /GUI/**/*.resx
    ignore:
      - Properties/
      - Localization/
      - HintTextBox.resx
    translation: /GUI/Localization/%locale%/%file_name%.%locale%.%file_extension%
  - source: /GUI/Properties/Resources.resx
    translation: /GUI/Properties/%file_name%.%locale%.%file_extension%
